name:                haskell-slime-simulation
version:             0.1.0.0
github:              "artembakhanov/haskell-slime-simulation"
license:             BSD3
author:              "Artem Bakhanov"
maintainer:          "artembakhanov@gmail.com"
copyright:           "2021 Artem Bakhanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/artembakhanov/haskell-slime-simulation#readme>

dependencies:
- base >= 4.7 && < 5
- base >= 4.7 && < 5
- accelerate
- colour-accelerate
- accelerate-io-bmp
- accelerate-llvm-native
- mwc-random-accelerate
- gloss-accelerate
- cuda
- accelerate-llvm-ptx


flags:
  enable-gpu:
    default: false
    manual:  true 
    description: On gpu or not





library:
  source-dirs: src
  when:
    - condition: flag(enable-gpu)
      then:
        cpp-options: -DACCELERATE_LLVM_PTX_BACKEND
      else:
        cpp-options: -DACCELERATE_LLVM_NATIVE_BACKEND

executables:
  haskell-slime-simulation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss
    - haskell-slime-simulation

    when:
    - condition: flag(enable-gpu)
      then:
        cpp-options: -DACCELERATE_LLVM_PTX_BACKEND
      else:
        cpp-options: -DACCELERATE_LLVM_NATIVE_BACKEND

tests:
  haskell-slime-simulation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-slime-simulation
